default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: DATABASE_HOST

development:
  <<: *default
  database: apprentice-quest-web
test:
  <<: *default
  database: apprentice-quest-web

production:
  <<: *default
  database: apprentice-quest-web
